# fly.toml app configuration file generated for sales-journal-aggregator-api on 2025-02-28T16:12:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sales-journal-aggregator-api'
primary_region = 'iad'
console_command = '/rails/bin/rails console'

[build]

[env]
  DATABASE_URL = 'sqlite3:///data/production.sqlite3'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
